#!/bin/bash
# Stops accidental commits to master and develop. https://gist.github.com/stefansundin/9059706

BRANCH=`git rev-parse --abbrev-ref HEAD`
echo "pre-commit hook"

if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then
  echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
  echo "If so, commit with -n to bypass this pre-commit hook."
  exit 1
fi

exit 0

# Don't forget to chmod -R a+x .git/hooks
